### ISSUE TITLE
When for NC 29

### ISSUE THREAD

**Issue by hobbycharken** [Thesola10/nextcloud-nextframe#3]
This is a very interesting app. When will i be available for NC29?

Regards

Anders Yuran

**Comment by Thesola10** [comment]
Have you tried enabling it (using "Allow incompatible app" button)? If there's no issue I can bump the compatible version list

**Comment by Fuseteam** [comment]
@Thesola10 a priliminary look seems to show it just works, directly visiting the iframe link also seems to correctly show the top bar. I haven't tried actually embedding it yet

Is there anything else i need to check?

**Comment by Thesola10** [comment]
@Fuseteam lgtm!

I'd just have a look at what the `Content-Security-Policy` header looks like, should include the upstream URLs you listed in the preferences pane

Apart from that, feel free to PR a metadata bump to NC29

**Comment by Fuseteam** [comment]
Will do

**Comment by Fuseteam** [comment]
yepp seems to list it

**Comment by Fuseteam** [comment]
@Thesola10 it seems that 28 is still listed as highest supported version in the store: https://apps.nextcloud.com/apps/nextframe do we need a new release for it to take effect perhaps? 28 is supposedly EOL in a month

**Comment by Thesola10** [comment]
boom, new release.
